apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.model }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName.model }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.model }}
    spec:
      containers:
        - name: {{ .Values.appName.model }}
          image: {{ .Values.image.modelServer }}
          imagePullPolicy: Never
          resources:
            limits:
              memory: "2048Mi"
              cpu: "4.0"
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              # value: redis-db-service
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.redis }}
                  key: hostname
            - name: REDIS_PORT
              # value: "6379"
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.redis }}
                  key: port
            - name: REDIS_PASSWORD
              # value: hunter2
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKey.redis }}
                  key: db_password
            - name: HF_MODEL
              # value: resnet18
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.modelServer }}
                  key: hf_model

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.model }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName.model }}
  ports:
    - port: 9000
      targetPort: 80
